# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://www.seanbode.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Sean Bode # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Witty & Hilarious Web Developer</h1>
     <p>I'm a kickass developer specializing in Rails, AngularJS, and Javascript.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: seanpaulbode@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr: https://www.flickr.com/photos/131302611@N07/
  github: https://github.com/seanbode
  google_plus:
  instagram: https://www.instagram.com/skippybench/?hl=en
  linkedin:  https://www.linkedin.com/in/seanpaulbode/
  pinterest: https://www.pinterest.com/seanbode/
  reddit:
  soundcloud: https://soundcloud.com/sean-bode
  stack_exchange:  https://stackexchange.com/users/7870411/sean
  steam: 
  tumblr: 
  twitter: https://twitter.com/seanbode
  wordpress: 
  youtube: https://www.youtube.com/channel/UCxqJ_GP33uDYXd4vNfSi2gA?view_as=subscriber

  # Scripts
  google_analytics: "UA-121459841-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
